### PR TITLE
busboy -> pez

### PR DESCRIPTION
**Pull request by davidmarkclements**

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
added as an owner on npm + github

**Comment by yoshuawuyts** [comment]
`v2.0.0` - the options object for `pez` is different from the one for `busboy` so yeah major

**Comment by davidmarkclements** [comment]
ok cool - if we're going major - what do you think to removing the res param (it's not used internally with either busboy or pez) and making the done param optional?

**Comment by davidmarkclements** [comment]
if you're into that, in this case, we could unpublish 2.0.0, do a patch and call 2.0.1 first major (if we act within 24hr window)

**Pull request merged**
